### ISSUE TITLE
Small Inconcistency in main vs nodejs documentation/examples.

### ISSUE THREAD

**Issue by ashvayka** [nicolsc/sigfox-downlink#3]
Hi!

The issue is about the downlink payload format. Main doc uses:
```
{
  '{{deviceId}}': {
	'downlinkData':{{data}}
 }
}
```

But [nodejs](https://github.com/sigfox/sigfox-downlink/tree/master/nodejs) uses:
`{"deviceId":"FAF7E","downlinkData":"70117f61a5ceec67"}`
I assume it should be:
`{"FAF7E": {"downlinkData":"70117f61a5ceec67"}}`

Is this correct assumption or both formats are valid? Please clarify.

**Comment by vrantrax** [comment]
The correct use is:
{"FAF7E": {"downlinkData":"70117f61a5ceec67"}}

**Comment by nicolsc** [comment]
You're right @vrantrax 
I pushed a quickfix, but this old sample code needs to be refreshed anyway
